// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ProbeResult {
    /**
     * Creates a new ProbeResult instance.
     * @param {Partial<ProbeResult>} [$$source = {}] - The source object to create the ProbeResult.
     */
    constructor($$source = {}) {
        if (!("rttMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rttMs"] = 0;
        }
        if (!("mbps" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["mbps"] = 0;
        }
        if (!("class" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["class"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProbeResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProbeResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProbeResult(/** @type {Partial<ProbeResult>} */($$parsedSource));
    }
}
