// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} serial
 * @returns {$CancellablePromise<void>}
 */
export function FetchBoot(serial) {
    return $Call.ByID(4107626767, serial);
}

/**
 * @param {string} serial
 * @returns {$CancellablePromise<$models.DownloadStatus>}
 */
export function Status(serial) {
    return $Call.ByID(2563507631, serial).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} serial
 * @returns {$CancellablePromise<void>}
 */
export function SyncFull(serial) {
    return $Call.ByID(464401843, serial);
}

// Private type creation functions
const $$createType0 = $models.DownloadStatus.createFrom;
