// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../internal/api/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as joy$0 from "../internal/joy/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<string>}
 */
export function BiosDir() {
    return $Call.ByID(3492866628);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function BiosOK() {
    return $Call.ByID(123595135);
}

/**
 * @param {number} index
 * @returns {$CancellablePromise<string>}
 */
export function CaptureJoy(index) {
    return $Call.ByID(1467877974, index);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function DataDir() {
    return $Call.ByID(4236054817);
}

/**
 * DeleteSave removes local cards, backups and sync state, plus the cloud copy.
 * @param {string} serial
 * @param {number} slot
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSave(serial, slot) {
    return $Call.ByID(1179805720, serial, slot);
}

/**
 * @returns {$CancellablePromise<$models.EmuStatus>}
 */
export function EmuStatus() {
    return $Call.ByID(3261282857).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function EnsureEmulator() {
    return $Call.ByID(899257803);
}

/**
 * @returns {$CancellablePromise<$models.FetchTier>}
 */
export function FetchTier() {
    return $Call.ByID(1361411542).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function ImportBIOS() {
    return $Call.ByID(4158901980);
}

/**
 * @returns {$CancellablePromise<joy$0.Device[]>}
 */
export function JoyDevices() {
    return $Call.ByID(3668664943).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<api$0.ProbeResult | null>}
 */
export function LastProbe() {
    return $Call.ByID(1152332816).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ListSaves scans the local cards library, newest serials first.
 * @returns {$CancellablePromise<$models.GameSaveInfo[]>}
 */
export function ListSaves() {
    return $Call.ByID(3924214832).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function PadBindings() {
    return $Call.ByID(316686757).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function PadButtons() {
    return $Call.ByID(3573199952).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {string} serial
 * @returns {$CancellablePromise<void>}
 */
export function Play(serial) {
    return $Call.ByID(2034665428, serial);
}

/**
 * @returns {$CancellablePromise<api$0.ProbeResult>}
 */
export function ProbeNow() {
    return $Call.ByID(1730317900).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * RestoreSave copies a local backup over the library and working cards and
 * clears sync state so the restored copy wins the next compare.
 * @param {string} serial
 * @param {number} slot
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function RestoreSave(serial, slot, name) {
    return $Call.ByID(1766289261, serial, slot, name);
}

/**
 * @param {string} button
 * @param {string} binding
 * @returns {$CancellablePromise<void>}
 */
export function SetPadBinding(button, binding) {
    return $Call.ByID(1531140916, button, binding);
}

/**
 * @param {any} pick
 * @returns {$CancellablePromise<void>}
 */
export function SetPicker(pick) {
    return $Call.ByID(3158803608, pick);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StopEmulator() {
    return $Call.ByID(2255344529);
}

/**
 * SyncSaves pulls newer cloud saves for one game (emulator must be stopped).
 * @param {string} serial
 * @returns {$CancellablePromise<void>}
 */
export function SyncSaves(serial) {
    return $Call.ByID(3743341221, serial);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Version() {
    return $Call.ByID(933621942);
}

// Private type creation functions
const $$createType0 = $models.EmuStatus.createFrom;
const $$createType1 = $models.FetchTier.createFrom;
const $$createType2 = joy$0.Device.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = api$0.ProbeResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.GameSaveInfo.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Map($Create.Any, $Create.Any);
const $$createType9 = $Create.Array($Create.Any);
