// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} serial
 * @returns {$CancellablePromise<void>}
 */
export function Clean(serial) {
    return $Call.ByID(1980062523, serial);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function DataDir() {
    return $Call.ByID(3567532165);
}

/**
 * @returns {$CancellablePromise<$models.GameInfo[]>}
 */
export function Games() {
    return $Call.ByID(2260639125).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} serial
 * @returns {$CancellablePromise<$models.GameInfo>}
 */
export function Progress(serial) {
    return $Call.ByID(1682077409, serial).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.GameInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
