// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DownloadStatus {
    /**
     * Creates a new DownloadStatus instance.
     * @param {Partial<DownloadStatus>} [$$source = {}] - The source object to create the DownloadStatus.
     */
    constructor($$source = {}) {
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("done" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["done"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("lastError" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DownloadStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadStatus(/** @type {Partial<DownloadStatus>} */($$parsedSource));
    }
}

export class EmuStatus {
    /**
     * Creates a new EmuStatus instance.
     * @param {Partial<EmuStatus>} [$$source = {}] - The source object to create the EmuStatus.
     */
    constructor($$source = {}) {
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("serial" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serial"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("sinceUnix" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sinceUnix"] = 0;
        }
        if (!("stage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["stage"] = "";
        }
        if (!("stageDone" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["stageDone"] = 0;
        }
        if (!("stageTotal" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["stageTotal"] = 0;
        }
        if (!("saveSeq" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["saveSeq"] = 0;
        }
        if (!("saveMsg" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["saveMsg"] = "";
        }
        if (!("saveOk" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["saveOk"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EmuStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EmuStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EmuStatus(/** @type {Partial<EmuStatus>} */($$parsedSource));
    }
}

export class FetchTier {
    /**
     * Creates a new FetchTier instance.
     * @param {Partial<FetchTier>} [$$source = {}] - The source object to create the FetchTier.
     */
    constructor($$source = {}) {
        if (!("probed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["probed"] = false;
        }
        if (!("class" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["class"] = "";
        }
        if (!("fetchSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fetchSize"] = 0;
        }
        if (!("prefetchDepth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["prefetchDepth"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FetchTier instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FetchTier}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FetchTier(/** @type {Partial<FetchTier>} */($$parsedSource));
    }
}

export class GameInfo {
    /**
     * Creates a new GameInfo instance.
     * @param {Partial<GameInfo>} [$$source = {}] - The source object to create the GameInfo.
     */
    constructor($$source = {}) {
        if (!("serial" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serial"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("supported" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["supported"] = false;
        }
        if (!("done" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["done"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("localPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["localPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GameInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GameInfo(/** @type {Partial<GameInfo>} */($$parsedSource));
    }
}

export class GameSaveInfo {
    /**
     * Creates a new GameSaveInfo instance.
     * @param {Partial<GameSaveInfo>} [$$source = {}] - The source object to create the GameSaveInfo.
     */
    constructor($$source = {}) {
        if (!("serial" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serial"] = "";
        }
        if (!("slots" in $$source)) {
            /**
             * @member
             * @type {SaveSlotInfo[]}
             */
            this["slots"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameSaveInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GameSaveInfo}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("slots" in $$parsedSource) {
            $$parsedSource["slots"] = $$createField1_0($$parsedSource["slots"]);
        }
        return new GameSaveInfo(/** @type {Partial<GameSaveInfo>} */($$parsedSource));
    }
}

export class SaveBackupInfo {
    /**
     * Creates a new SaveBackupInfo instance.
     * @param {Partial<SaveBackupInfo>} [$$source = {}] - The source object to create the SaveBackupInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("mtime" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["mtime"] = 0;
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveBackupInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SaveBackupInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveBackupInfo(/** @type {Partial<SaveBackupInfo>} */($$parsedSource));
    }
}

export class SaveSlotInfo {
    /**
     * Creates a new SaveSlotInfo instance.
     * @param {Partial<SaveSlotInfo>} [$$source = {}] - The source object to create the SaveSlotInfo.
     */
    constructor($$source = {}) {
        if (!("slot" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["slot"] = 0;
        }
        if (!("present" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["present"] = false;
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("mtime" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["mtime"] = 0;
        }
        if (!("synced" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["synced"] = false;
        }
        if (!("backups" in $$source)) {
            /**
             * @member
             * @type {SaveBackupInfo[]}
             */
            this["backups"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveSlotInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SaveSlotInfo}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("backups" in $$parsedSource) {
            $$parsedSource["backups"] = $$createField5_0($$parsedSource["backups"]);
        }
        return new SaveSlotInfo(/** @type {Partial<SaveSlotInfo>} */($$parsedSource));
    }
}

export class ServerEntry {
    /**
     * Creates a new ServerEntry instance.
     * @param {Partial<ServerEntry>} [$$source = {}] - The source object to create the ServerEntry.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["token"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServerEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerEntry(/** @type {Partial<ServerEntry>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = SaveSlotInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = SaveBackupInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
