// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<string>}
 */
export function Active() {
    return $Call.ByID(632273176);
}

/**
 * @returns {$CancellablePromise<$models.ServerEntry>}
 */
export function ActiveEntry() {
    return $Call.ByID(3047503484).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} name
 * @param {string} url
 * @param {string} username
 * @param {string} password
 * @returns {$CancellablePromise<void>}
 */
export function AddServer(name, url, username, password) {
    return $Call.ByID(2156525450, name, url, username, password);
}

/**
 * @param {string} url
 * @returns {$CancellablePromise<$models.ServerEntry>}
 */
export function Entry(url) {
    return $Call.ByID(1878378342, url).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function RemoveServer(url) {
    return $Call.ByID(3445007501, url);
}

/**
 * @returns {$CancellablePromise<$models.ServerEntry[]>}
 */
export function Servers() {
    return $Call.ByID(354339326).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function SetActive(url) {
    return $Call.ByID(1057472144, url);
}

/**
 * @param {string} url
 * @param {string} username
 * @param {string} password
 * @returns {$CancellablePromise<void>}
 */
export function TestConnection(url, username, password) {
    return $Call.ByID(118002754, url, username, password);
}

// Private type creation functions
const $$createType0 = $models.ServerEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
